# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on: pull_request

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: joschi/setup-jdk@v1
      with:
        java-version: 1.11
        architecture: x64
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
